# This workflow performs the following checks:
#   - code is correctly formatted
#   - code builds
#   - all tests pass
#   - no unhandled clippy warnings

name: Rust CI

on:
  push:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check code format
        run: cargo fmt --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if code builds
        run: cargo build --locked

